apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

configurations:
  - kustomizeconfig.yaml
  
# components:
#   - github.com/ocm-sop/apps-domain-tls-cert?ref=main

secretGenerator:
  - name: sso-host-client-creds
    namespace: openshift-config
    type: "Opaque"
    literals:
      - clientSecret=MY_VERY_LONG_AND_WRONG_OCP_CLIENT_SECRET

resources:
  - oauth.yaml