apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  namespace: openshift-config
spec:
  identityProviders:
    - mappingMethod: claim
      name: sso
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
            - email
            - name
        clientID: sso-host-client-id
        clientSecret:
          name: sso-host-client-creds
        extraAuthorizeParameters:
          include_granted_scopes: "true"
        extraScopes:
          - email
          - profile
          - groups
          - 'federated:id'
          - offline_access
        issuer: "https://sso.$(APPS_DOMAIN)"
      type: OpenID